name: Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Build
        run: bash scripts/build.sh

      - uses: actions/upload-artifact@v7
        with:
          name: rime-wanxiang-dist-${{ github.ref_name }}
          if-no-files-found: error
          path: dist/rime-wanxiang-*.zip
