name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test
    paths-ignore:
      - '**/*.md'
  pull_request:

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Download Mira
        uses: robinraju/release-downloader@v1
        with:
          repository: rimeinn/mira
          latest: true
          fileName: mira-linux-x86_64
          out-file-path: tests

      - name: Rename Mira binary
        working-directory: tests
        run: |
          mv mira-linux-x86_64 mira
          chmod +x mira

      - name: Build
        run: bash scripts/build.sh --no-archive

      - name: Run tests
        id: run-tests
        working-directory: tests
        run: python mira_report.py ./mira wanxiang.test.yaml wanxiang_pro.test.yaml --report-dir reports

      - uses: ctrf-io/github-test-reporter@v1
        if: ${{ !cancelled() }}
        with:
          report-path: ./tests/reports/*.json
          github-report: true

      - uses: ctrf-io/github-test-reporter@v1
        if: ${{ !cancelled() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          report-path: ./tests/reports/*.json
          pull-request-report: true

      - uses: actions/upload-artifact@v7
        if: ${{ steps.run-tests.outcome == 'failure' }}
        with:
          path: dist
